### ISSUE TITLE
PR back to Mads

### ISSUE THREAD

**Issue by OzBob** [failwyn/BundlerMinifier#1]
Jason - this is brilliant and a life saver - i had completely uninstalled 2019. Then discovered I needed this and the webcomplier in 2022. thanks again.

Send Mads a Tweet and ask him to merge your PR

**Comment by ScottRFrost** [comment]
Created https://github.com/madskristensen/BundlerMinifier/pull/575

**Comment by failwyn** [comment]
@ScottRFrost Thanks, They’re critical extensions for my company, so I’m more than happy to do it! It was nice to have Mads’ blessing as well!
