### ISSUE TITLE
A valid UTF32 value is between 0x000000 and 0x10ffff...

### ISSUE THREAD

**Issue by piotrm73** [failwyn/BundlerMinifier#13]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 2.9.3

### Description
I have strange error and can't minifi css file
"A valid UTF32 value is between 0x000000 and 0x10ffff, inclusive, and should not include surrogate codepoint values"

what do i need to look for to correct it?

**Comment by failwyn** [comment]
Is there any way you can supply a small sample project so that I can reproduce and debug the issue?

**Comment by piotrm73** [comment]
unfortunately it is a large project with a lot of sass files and I don't know which file caused the error... Maybe this error has something to do with the fact that I was working with this project in both Visual Studio and Visual Studio Code... after cleaning the project and re-cloning the error disappeared... so this issue can be closed for now..
