### ISSUE TITLE
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by jonsagara** [failwyn/BundlerMinifier#18]
### Installed product versions
- Visual Studio: Visual Studio Professional 2022
- This extension: 2.9.3

### Description
Hi, when we try to install the extension, we get the following exception:

```
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
```

I use this all the time on my x64 Windows 11 machine, but I have a colleague who is trying to install it in Parallels running on an M1 MacBook Pro, and he gets this error when trying to install the extension.

Is there a workaround for this?

### Steps to recreate
1. Download .vsix from https://marketplace.visualstudio.com/items?itemName=Failwyn.BundlerMinifier64
2. Try to install it

### Current behavior
The extension fails to install

### Expected behavior
The extension should install properly.

### Log file

<details>
<summary>Click to expand</summary>

```
1/12/2023 12:07:43 PM - Microsoft VSIX Installer
1/12/2023 12:07:43 PM - -------------------------------------------
1/12/2023 12:07:43 PM - vsixinstaller.exe version:
1/12/2023 12:07:43 PM - 17.4.2120
1/12/2023 12:07:43 PM - -------------------------------------------
1/12/2023 12:07:43 PM - Command line parameters:
1/12/2023 12:07:43 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\BundlerMinifierVsix.vsix
1/12/2023 12:07:43 PM - -------------------------------------------
1/12/2023 12:07:43 PM - Microsoft VSIX Installer
1/12/2023 12:07:43 PM - -------------------------------------------
1/12/2023 12:07:44 PM - Initializing Install...
1/12/2023 12:07:45 PM - Extension Details...
1/12/2023 12:07:45 PM - 	Identifier         : 5783ce1f-b23d-4e84-87a4-6b2cbe9e0602
1/12/2023 12:07:45 PM - 	Name               : Bundler & Minifier 2022+
1/12/2023 12:07:45 PM - 	Author             : Jason Moore
1/12/2023 12:07:45 PM - 	Version            : 2.9.3
1/12/2023 12:07:45 PM - 	Description        : Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.
1/12/2023 12:07:45 PM - 	Locale             : en-US
1/12/2023 12:07:45 PM - 	MoreInfoURL        : https://github.com/failwyn/BundlerMinifier
1/12/2023 12:07:45 PM - 	InstalledByMSI     : False
1/12/2023 12:07:45 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/12/2023 12:07:45 PM -
1/12/2023 12:07:45 PM - 	SignatureState     : Unsigned
1/12/2023 12:07:45 PM - 	Supported Products :
1/12/2023 12:07:45 PM - 		Microsoft.VisualStudio.Community
1/12/2023 12:07:45 PM - 			Version : [17.0,)
1/12/2023 12:07:45 PM - 			ProductArchitecture : amd64
1/12/2023 12:07:45 PM -
1/12/2023 12:07:45 PM - 	References         :
1/12/2023 12:07:45 PM - 	Prerequisites      :
1/12/2023 12:07:45 PM - 		-------------------------------------------------------
1/12/2023 12:07:45 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/12/2023 12:07:45 PM - 		Name         : Visual Studio core editor
1/12/2023 12:07:45 PM - 		Version      : [17.0,)
1/12/2023 12:07:45 PM -
1/12/2023 12:07:45 PM - Signature Details...
1/12/2023 12:07:45 PM - 	Extension is not signed.
1/12/2023 12:07:45 PM -
1/12/2023 12:07:45 PM - Searching for applicable products...
1/12/2023 12:07:45 PM - Found installed product - Visual Studio Professional 2022
1/12/2023 12:07:45 PM - Found installed product - Global Location
1/12/2023 12:07:45 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
</details>

**Comment by jpgoyne** [comment]
Here are the details. My development environment is the one @jonsagara referred to in his post.
1. Apple M1 Max
2. Version 17.4.4 Microsoft Visual Studio Professional 2022 (ARM 64-bit)
3. No

**Comment by failwyn** [comment]
Someone reported a similar issue with WebCompiler, would you mind trying that extension to see if you get the same result?

[https://github.com/failwyn/WebCompiler/issues/51#issue-1351143975](https://github.com/failwyn/WebCompiler/issues/51#issue-1351143975)

**Comment by failwyn** [comment]
Ignore my last comment, Keep an eye out for a new version here, I can't test it, so I won't upload it to the VS Marketplace until you report back. I'll try to get it uploaded in the next day or so.

**Comment by failwyn** [comment]
Can you give this a try and see if it works? The vsix is in the zip file.

[BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/10445493/BundlerMinifierVsix.zip)

**Comment by jpgoyne** [comment]
I was able to install the extension but it doesn't load when Visual Studio starts up. Please see the attached ActivityLog for error details.
[ActivityLog.txt](https://github.com/failwyn/BundlerMinifier/files/10462421/ActivityLog.txt)

**Comment by jpgoyne** [comment]
Here is an updated ActivtyLog with assembly bind failure logging enabled.
[ActivityLog.txt](https://github.com/failwyn/BundlerMinifier/files/10470940/ActivityLog.txt)

**Comment by failwyn** [comment]
Can you give this one a try? Sorry for the trial and error...

[BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/10471131/BundlerMinifierVsix.zip)

**Comment by jpgoyne** [comment]
Looks like the same error. Attached is the log. Thank you for taking a look.
[ActivityLog.txt](https://github.com/failwyn/BundlerMinifier/files/10482514/ActivityLog.txt)

**Comment by failwyn** [comment]
I'm gonna check around and see if any of my friends have an ARM64 machine they aren't using; I have no problem continuing to post versions for you to try if you really want to get it working, but I feel bad making you test every version I build...

**Comment by ronmichael** [comment]
FWIW I followed Microsoft's instructions here - https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/ - and was able to modify Bundler & Minifier so that it'd install in Visual Studio 2022 ARM on a M2 Macbook with Parallels. Seems to work normally. 

The instructions did not work as well for WebCompiler. I get the errors below which I'm not sure what to do with:

Error | CS1566 | Error reading resource 'WebCompiler.Node.node_modules.7z' -- 'Could not find file 'C:\git\WebCompiler\src\WebCompiler\Node\node_modules.7z'.' | WebCompiler (net4.8) | C:\git\WebCompiler\src\WebCompiler\CSC | 1 | Active

Error | CS0006 | Metadata file 'C:\git\WebCompiler\src\WebCompiler\bin\Debug\net4.8\WebCompiler.exe' could not be found | WebCompilerVsix | C:\git\WebCompiler\src\WebCompilerVsix\CSC | 1 | Active

**Comment by failwyn** [comment]
@ronmichael  Would you mind submitting a pull request? I followed a few articles about ARM64 support, but the users testing it for me are still getting errors.

**Comment by ronmichael** [comment]
Sorry, this is stupid, but I rarely submit pull requests and my Git client (SourceTree) just keeps giving me auth errors when I try to do it. So... here are some screenshots of the 4 changes that I made to get it to work. Hope this helps.

![image](https://user-images.githubusercontent.com/797230/216454513-cf0776ab-8a39-4669-b628-bcbf947f6862.png)
![image](https://user-images.githubusercontent.com/797230/216454539-3133ed9f-9110-456c-9407-fc099da03cf5.png)

**Comment by failwyn** [comment]
I think it was the build tools version that I was missing! Thanks for this, the articles said to update the build tools in nuget, but I didn't see them, so I just skipped that part, I should have checked the proj file directly; I'll hopefully have time to post a test version today to see if I can get it working on both platforms.

**Comment by jacklawry** [comment]
@failwyn Did you manage to get this version working? 
I am getting this same issue M2 MacBook Pro

**Comment by failwyn** [comment]
@jacklawry Sorry for the delay, work has been very busy, I still don’t have a machine to test it on, but I’ll upload a version here in the morning if you want to test it out.

**Comment by jacklawry** [comment]
> @jacklawry Sorry for the delay, work has been very busy, I still don’t have a machine to test it on, but I’ll upload a version here in the morning if you want to test it out.

No problem, Yes I would be more than happy to give it a test once it is ready.

**Comment by failwyn** [comment]
@jacklawry  Fingers crossed that this one works...

[BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/10828456/BundlerMinifierVsix.zip)

**Comment by BenDTU** [comment]
Gave it a shot and it gave this error:
```Could not load file or assembly 'NUglify, Version=1.17.10.0, Culture=neutral, PublicKeyToken=15bc7810aec21b5e' or one of its dependencies. The system cannot find the file specified.```

Granted I don't normally use this extension so I'm not sure if I missed something - I'm normally a Web Compiler++ user.

**Comment by jacklawry** [comment]
> @jacklawry Fingers crossed that this one works...
> 
> [BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/10828456/BundlerMinifierVsix.zip)

@failwyn I downloaded and installed this version in VS 2022 Community edition in Win 11 (Arm) and it seems to have installed correctly but I don't get the option to convert from scss to css? Is there another step to do this?

**Comment by jacklawry** [comment]
Just realised this was the chat for Builder Minifier not (Web Compiler) - 
Hopefully once this is working the same fix can be applied to Web Compiler as per this issue (https://github.com/failwyn/WebCompiler/issues/51)

I have also just tried to minify the css file and get the same error as @BenDTU 

```
Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | (Bundler & Minifier) Could not load file or assembly 'NUglify, Version=1.17.10.0, Culture=neutral, PublicKeyToken=15bc7810aec21b5e' or one of its dependencies. The system cannot find the file specified.
```

Hope this helps and happy to test future versions as WC is the only plugin I need that isn't working on Parallels on my MacBook Pro M2.

**Comment by failwyn** [comment]
@jacklawry  I think I found the issue that caused this; I'm gonna test the new build on my machine to make sure I didn't break anything on the x64 side, then I'll post a new version here for you to test on amd64. Thanks for the help with this!

// once this is working, I plan to update WebCompiler too; WebCompiler is a bit more complicated

**Comment by jacklawry** [comment]
@failwyn No problem happy to test and help get this working

**Comment by jacklawry** [comment]
@failwyn I know you are busy just wondering if there was any update on this?

**Comment by failwyn** [comment]
I have been using this on Windows x64 for the last week and the changes do not appear to have caused any issues for my use cases; let me know if it installs and works on the arm64 machine; if it doesn't work, just post as much info on the error as you can; I appreciate your help, I'm still looking for someone with an arm64 machine they can part with for a short while.

[BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/10932823/BundlerMinifierVsix.zip)

**Comment by jacklawry** [comment]
> I have been using this on Windows x64 for the last week and the changes do not appear to have caused any issues for my use cases; let me know if it installs and works on the arm64 machine; if it doesn't work, just post as much info on the error as you can; I appreciate your help, I'm still looking for someone with an arm64 machine they can part with for a short while.
> 
> [BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/10932823/BundlerMinifierVsix.zip)

@failwyn - This installs and seems to work fine on my M2 MacBook Pro (running Parallels & Windows 11 ARM64). 
No error given and when I selected Re-bundle file the change were copied over as expected to the .min.css file.  

Does this mean a similar update to WebCompiler can begin? Again happy to test anything as it is ready.

**Comment by failwyn** [comment]
@jacklawry - It's great to finally hear that it worked!! I'll try to publish this version to the Visual Studio Marketplace this week, then I'll start looking at WebCompiler right after; hopefully it will go much smoother now that I got one of them working.

Just a note, CompileOnBuild may not work for you right now because it downloads the dll from nuget and I have not updated nuget with this version yet.

**Comment by jacklawry** [comment]
@failwyn just wondering if you had anything to test on the WebCompiler Arm version yet?

**Comment by failwyn** [comment]
Trying to get to it, just swamped at work at the moment.

**Comment by jacklawry** [comment]
> Trying to get to it, just swamped at work at the moment.

Totally understand @failwyn ... For now (& if it helps anyone else) as a work around I have installed "[Chocolatey package manager](https://chocolatey.org/)"  then once that is installed Install [SASS](https://sass-lang.com/install) and then via terminal get sass to watch my scss folder for changes and build the css. Not quite the same as WebCompiler but does allow scss/sass to be compiled in Arm64 on a MacBook Pro M2. 

Still happy to test anything as you get time.

**Comment by failwyn** [comment]
Version 2.9.6 is now available on the Visual Studio Marketplace. I also uploaded the nuget package which was still referencing the original version by Mads; please let me know if any issues arise, I had a few people test before release, so hopefully it's smooth.

**Comment by MrSethT** [comment]
I am now getting this error 
![image](https://user-images.githubusercontent.com/6687355/227623900-d7a37c12-d9bf-4a6b-8499-ba873d9a9343.png)

xml says 
<description>SetSite failed for package [BundlerMinifierPackage]Source: &apos;BundlerMinifierVsix&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at BundlerMinifierVsix.BundlerMinifierPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>

**Comment by failwyn** [comment]
@MrSethT Can you give some details on your system and version of Visual Studio?

**Comment by MrSethT** [comment]
Sure,
---------------------VS----------------------
Microsoft Visual Studio Professional 2022
Version 17.3.6
VisualStudio.17.Release/17.3.6+32929.385
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA585
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

Bundler & Minifier   2.9.6
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Color Preview   1.0.22
Shows a color preview in front of all named colors, hex, rgb and hsl values in CSS files.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22179.3
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.22179.3
Profiling support for Python projects.

Python with Pylance   17.0.22179.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.308 (d17-3@56b9f7e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.217 (remotes/origin/d17-3@b81db1dcc0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6


Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.


------------------------------My System-----------------------
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by failwyn** [comment]
Can you try upgrading Visual Studio to 17.4 or newer?

**Comment by MrSethT** [comment]
I think that fixed that error, thanks!  Now it's giving me an "object not set to instance of and object" error in the min version of my js.  I have looked for errors in the src version and don't see any... you think it's related or sperate?

**Comment by failwyn** [comment]
If you can provide a small same project to reproduce the error, I can take a look at it

**Comment by MrSethT** [comment]
I tried making a smaller project with that file in it to minify, no error.
I tried forking BundleMinifier to see the error myself, console gets no error, minify command gets no error.  How do I debug the buildtask?

**Comment by failwyn** [comment]
@jacklawry - I uploaded my first attempt at arm64 support for WebCompiler.

https://github.com/failwyn/WebCompiler/issues/51

**Comment by failwyn** [comment]
Would someone mind testing this to let me know if it still works on arm64? I downgraded some of the Visual Studio dlls to try to restore compatibility with versions prior to 17.4; I really appreciate any and all help =)

[BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/11079191/BundlerMinifierVsix.zip)

**Comment by MrSethT** [comment]
I have discovered a workaround that I will be using from now on. I plan to remove any instances of 'async' or 'await' from the source JavaScript code. In my sample project I tried to make to send you, the source code was minimized successfully, and the project built without any issues, even with 'async/await'. However, in the full project, although the JavaScript is successfully minified, it fails to build due to an error message that reads 'Object not set to instance of an object' from MinifyBuild referencing the source JavaScript code.

Thank you for your responses and for this great project. I consider all my issues to be closed.

**Comment by failwyn** [comment]
Sorry for the long delay on this and thank you so much for the help testing it, 2.9.8 is now available on the Visual Studio Marketplace and is once again compatible with version 17.0+ for x64 and 17.4+ for arm64.

**Comment by jacklawry** [comment]
> Would someone mind testing this to let me know if it still works on arm64? I downgraded some of the Visual Studio dlls to try to restore compatibility with versions prior to 17.4; I really appreciate any and all help =)
> 
> [BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/11079191/BundlerMinifierVsix.zip)
> 
> @jacklawry If you have some spare time =)

@failwyn Yes this also seems to still work on Arm64
