### ISSUE TITLE
After installing 2.9.6, "Update all files" fails with FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0...'

### ISSUE THREAD

**Issue by jonsagara** [failwyn/BundlerMinifier#19]
### Installed product versions
- Visual Studio: 2022 Preview (17.6.0 Preview 2.0) (64-bit)
- This extension: 2.9.6
- Windows x64

### Description
I got a notification the Bundler & Minifier had an update, so I installed it and restarted Visual Studio.

When I opened a project and clicked "Update all files" from the Task Runner Explorer, I got an exception about not being able to load Newtonsoft.Json.

### Steps to recreate
1. Have Bundler & Minifier 2.9.3 installed
2. Open Visual Studio 2022 Preview
3. Get notification that an update to Bundler & Minifier is available
4. Update it
5. Close VS
6. Reopen VS after the install is complete
7. In the Task Runner Explorer, right-click "Update all files" and click Run

### Current behavior
I get an exception in the output:

```
C:\DevMyCompany\MyProject\src\MyProject> c:\users\jon\appdata\local\microsoft\visualstudio\17.0_a4efff78\extensions\ws2axrth.0xo\BundlerMinifierConsole.exe "C:/DevMyCompany/MyProject/src/MyProject/bundleconfig.json"
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at BundlerMinifier.BundleHandler.TryGetBundles(String configFile, IEnumerable`1& bundles)
   at BundlerMinifierConsole.Program.GetConfigFileFromArgs(String[] args, String& configPath)
   at BundlerMinifierConsole.Program.Main(String[] args)
Process terminated with code -532462766.
```

### Expected behavior
The extension should bundle and minify as it had previously in 2.9.3.

**Comment by hardhub** [comment]
Same issue...

```
System.IO.FileLoadException: 'Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
```

**Comment by jonsagara** [comment]
Workaround: 

* Uninstall 2.9.6
* Download 2.9.3 from here and install it manually:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Failwyn/vsextensions/BundlerMinifier64/2.9.3/vspackage

BTW, @failwyn, I appreciate you and all the work you do for these extension.

**Comment by failwyn** [comment]
It's odd that Saving a file, Right Clicking bundleconfig.json -> Bunder & Minifier -> Update Bundles, and Enable Bundle on Build work, but Update all files in task runner doesn't... I've never used the Task Runner, so I'll have to dig through the code and find how it is implemented to see why it can't find Newtonsoft...

**Comment by failwyn** [comment]
It's putting Newtonsoft.JSON.dll version 9 in the vsix package for some reason even though every reference is to version 13...

**Comment by failwyn** [comment]
Found it,

**Comment by failwyn** [comment]
I just published 2.9.7 to the Visual Studio Marketplace, it should be available in a few minutes. Sorry for that, I didn't notice that the newtonsoft.json.dll was copied into the project folder to be included in the vsix.

**Comment by jonsagara** [comment]
Great - thank you! I'll try it when I get home tonight. 👍🏻

**Comment by jonsagara** [comment]
Beautiful - works perfectly, @failwyn. Thank you!

Do you need me to keep this issue open for any reason, or can I close it?

**Comment by failwyn** [comment]
Glad to hear it worked!!
