### ISSUE TITLE
JavaScriptOptions:  multiline output injecting "2" into generated min.js instead of indent character

### ISSUE THREAD

**Issue by philblackburn** [failwyn/BundlerMinifier#20]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: v 2.9.8

### Description
The output from the minifier, when using multiline option injects numeric value "2" when using default settings for indentSpaces.  Setting the indentSpaces to any number insert that number into the code.
The only way to have the code generate valid script is to set indentSpaces to "  "

### Steps to recreate
1. Take any javascript input, for example:
`function sample() {
    doSomthing();
};
 `
2. Options set as
  `"minify": {
      "outputMode": "multipleLines"
    }`
  ie. "indentSize"  unset,
or
 `"minify": {
      "indentSize"  2,
      "outputMode": "multipleLines"
    }`

4.   process minify
5.  Output is:
 `function sample()
{
2doSomthing()
}`

### Current behavior
The tab spacing is replaced to 2 for each expected tab

### Expected behavior

 `function sample()
{
  doSomthing()
}`

### Cause:

JavaScriptOptions.cs sets the default Indent like so...
`37:            settings.Indent = GetValue(bundle, "indentSize", "2");`

`settings.Indent` is expecting a string that represents a single tab space. 

It would work if this line was written as:
       `settings.IndentSize = GetValue(bundle, "indentSize", "2");`
however, with IndentSize being obsolete you may want to take a different approach

**Comment by failwyn** [comment]
Thanks for this, I'll try to get a fix out today.

**Comment by WolfpackSoftware** [comment]
Also run into this issue.  I couldn't get the indentSpaces approach to work for me.  I note that the wiki link still points to Mads' older version, which I expect is largely correct but perhaps is now diverging from the @failwyn implementation.

My temporary workaround is to set outputMode back to singleLine.

**Comment by failwyn** [comment]
2.9.9 should be now available on the Visual Studio Marketplace, let me know if you have any issues.

**Comment by failwyn** [comment]
It looks like it took a while for Microsoft to verify it yesterday, it's there now.

**Comment by philblackburn** [comment]
Thanks @failwyn,  It works a treat.  And a very response time too 👍

**Comment by WolfpackSoftware** [comment]
Also confirmed available and working.  Thanks @failwyn !
