### ISSUE TITLE
Can't minify js file

### ISSUE THREAD

**Issue by Mikael-Pothier** [failwyn/BundlerMinifier#21]
### Installed product versions
- Visual Studio: Professional 2022
- This extension: 2.9.9

### Description
Hi I am trying to minify some js file but I dont get the option in the context menu. Here is what I get in the menu. 
![image](https://github.com/failwyn/BundlerMinifier/assets/8630076/aec3f18a-362d-497a-aa78-55fee7182305)

If I right click on a css file it does work correctly.

### Steps to recreate
1. Right click on a js file

### Expected behavior
have the option to minify a js file when the context menu open.

**Comment by failwyn** [comment]
Can you try reinstalling the BundlerMinifier extension? It doesn't look like it installed successfully.

**Comment by Mikael-Pothier** [comment]
After reinstalling everything works correctly. Thanks for the help!
