### ISSUE TITLE
When Minifying "0fr", the unit got removed.

### ISSUE THREAD

**Issue by Philipp-Strobl** [failwyn/BundlerMinifier#24]
### Installed product versions
- Visual Studio: 2022 17.6.3
- This extension: 2.9.9

### Description
When Minifying "0fr", the unit got removed.

### Steps to recreate
1. Create a class and add for example "grid-template-rows" with the value of "0fr".
2. Minify code
3. Check in Browser (tested Chrome 114.0.5735.134, FireFox 114.0.2 and Edge 114.0.1823.58)

### Current behavior
For some reason the unit "fr" is removed when the value 0 is provided.

### Expected behavior
The unit "fr" is not removed, like on %.

**Comment by failwyn** [comment]
We use NUglify to minimize the css; the removal of the fr is probably an optimization; Is there a noticeable difference between 0fr and 0?

**Comment by Philipp-Strobl** [comment]
Ya there is.
If you want to transition for example "grid-template-columns" from "1fr" to "0fr" and the unit is removed, no animation is shown.

**Comment by failwyn** [comment]
I'd post this issue on the NUglify GitHub page and see what they say about it.

**Comment by Philipp-Strobl** [comment]
Cool, thank you.

**Comment by p-strobl** [comment]
Hey @failwyn, any new knowledge here?

**Comment by failwyn** [comment]
Did you add the issue to the NUglify repo? Once I get some free time, I can see if I can fix the issue for them and submit a pull request, if accepted I'll publish a new version of the extensions.

**Comment by failwyn** [comment]
I submitted a PR on NUglify that will fix this issue; I have a few other NUglify issues to look at, then I'll publish a new version.

**Comment by pvh-archifact** [comment]
For a temporary workaround until [nuglify solved the issue](https://github.com/trullock/NUglify/pull/388) we can use fractional:
grid-template-columns: 1fr **.00001fr**;

**Comment by failwyn** [comment]
@pvh-archifact  This should be fixed in the latest release, are you still seeing the issue?

**Comment by pvh-archifact** [comment]
correct, running 2.9.11, left un-minified source, right minified source:
![image](https://github.com/user-attachments/assets/5f2f0a61-138a-4c1f-a9e3-51da29c8bb20)

**Comment by failwyn** [comment]
@pvh-archifact  That's really odd, I can't replicate the issue... Can you post your bundleconfig.json?
css:
```
.something {
    grid-template-columns: 1fr 0fr;
}
```

min.css:
```
.something{grid-template-columns:1fr 0fr}
```

**Comment by pvh-archifact** [comment]
Nothing special about the bundleconfig:
{
  "outputFileName": "wwwroot/css/local_bundle.css",
  "inputFiles": [
    "wwwroot/local-css/local-fonts.css",
    "wwwroot/local-css/local.css",
    "wwwroot/local-css/theme-all.css"
  ],
  "minify": {
    "enabled": true,
    "renameLocals": true
  }
},


Maybe the way its put in css?
#header .nav #todo-menu .dropdown-menu li a:not(.btn),
#header .nav #todo-menu .dropdown-menu li button:not(.btn) {
  display: grid;
  grid-template-columns: 1fr 0fr;
  gap:1em;
}

**Comment by failwyn** [comment]
This is the result I get when minimizing your css; can you try uninstalling and reinstalling the extension?

```
#header .nav #todo-menu .dropdown-menu li a:not(.btn),#header .nav #todo-menu .dropdown-menu li button:not(.btn){display:grid;grid-template-columns:1fr 0fr;gap:1em}
```

**Comment by pvh-archifact** [comment]
interesting. that seems to do the trick.
![image](https://github.com/user-attachments/assets/a1be1015-d6ac-451c-9517-d88286e67115)

**Comment by failwyn** [comment]
Interesting, it sounds like when you upgraded to 2.9.11 it somehow didn't update the NUglify.dll... Not sure how that would happen, but I'm glad to hear it's working for you!
