### ISSUE TITLE
VS 2022 Freezes

### ISSUE THREAD

**Issue by msbuildnet** [failwyn/BundlerMinifier#25]
### Installed product versions
- Visual Studio: 17.7.1
- This extension: 2.9.9

### Description
VS is freezing when the plugin automatically tries to minify CSS files
it works when trigerred manually with the embedded task explorer

bundleconfig.json

[
  {
    "outputFileName": "assets/common.min.css",
    "inputFiles": [
      "styles/*.css"
    ]
  }
]

Thank you

**Comment by msbuildnet** [comment]
Edit : All other plugins are disabled !
only slowcheetah and this plugin are active 

new freeze on file save (trigerring the minification) ...

**Comment by failwyn** [comment]
Does this happen for you on a non preview version of Visual Studio?

**Comment by msbuildnet** [comment]
17.7.1 is not in preview !

Cordialement,

Frédéric SAMSON

***@***.***

De : Jason Moore ***@***.***>
Envoyé : vendredi 25 août 2023 20:44
À : failwyn/BundlerMinifier ***@***.***>
Cc : Frédéric SAMSON ***@***.***>; Author ***@***.***>
Objet : Re: [failwyn/BundlerMinifier] VS 2022 Freezes (Issue #25)


Does this happen for you on a non preview version of Visual Studio?

**Comment by failwyn** [comment]
Finally got the notification that it’s officially out; I’ll update and test first thing Monday morning and let you know what happens.

**Comment by failwyn** [comment]
I updated to 17.7.2 and everything is working normally for me. Would you be able to check your logs for more information on the error that is causing Visual Studio to freeze?
