### ISSUE TITLE
Link back to the issue in the original extension

### ISSUE THREAD

**Issue by AlfonsoML** [failwyn/BundlerMinifier#3]
Thank you very much for porting this extension to 2022.

Would it be possible to add a link to https://github.com/madskristensen/BundlerMinifier/issues/566#issuecomment-898591171 in the Overview page at VS Marketplace? https://marketplace.visualstudio.com/items?itemName=Failwyn.BundlerMinifier64&ssr=false#overview

That would help a lot for anyone trying to figure out what's going on.

**Comment by failwyn** [comment]
@AlfonsoML Done!
