### ISSUE TITLE
Does the VSCode tasks still work?

### ISSUE THREAD

**Issue by mwkcoding** [failwyn/BundlerMinifier#36]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 2.9.9

### Description
I'd like to use the Visual Studio Code tasks [as defined in the wiki](https://github.com/madskristensen/BundlerMinifier/wiki#visual-studio-code). However, it seems to be requiring .NET Core 2.0 Runtime which is way past EOL and not cross-platform. Can this be upgraded? Our use-case is that front-end developers would like to not have to open Visual Studio to bundle our JS files and I'm working towards fixing that. It'd be nice if we can keep using this extension as it would be the least invasive DX improvement.

### Steps to recreate
1. Follow guide to make VSCode task for bundling.
2. Run task
3. See error

### Current behavior
Currently the task fails with the following output:
![image](https://github.com/user-attachments/assets/3497b83e-02ef-4359-a6b4-907a78f32660)

### Expected behavior
The task should run without issues and not require Visual Studio to be present or open.

**Comment by failwyn** [comment]
It looks like the error is saying that you need to install .net core 2.0

**Comment by mwkcoding** [comment]
Sure. But as mentioned we can't use .NET Core 2.0. All projects in our solution is running .NET 6.
Either way, it's the original author's package. Have you made a more up-to-date version of it and published?

**Comment by bakerhillpins** [comment]
Am I misunderstanding something here, it seems you're using a different package? 

![image](https://github.com/user-attachments/assets/f58d82a5-ba26-4e80-9158-c6d447cef11b)

Regardless, a PR for this here should be relatively simple too as it should compile just fine with .NET6/8.

**Comment by mwkcoding** [comment]
@bakerhillpins I'm using the package linked in the wiki that is being linked to from this repo. I'm aware that the wiki being linked to is the one made by the original author. If there's a different package I should use, I'd like to know which one that would be.

**Comment by failwyn** [comment]
It's the correct package, I never use the Task Runner, so I'm not too familiar with the code, but it looks like the issue is from the BundlerMinifier\src\BundlerMinifier\build\BuildBundlerMinifier2022.targets file; it uses the netstandard2.0 build when running in .net core; I just merged a PR from another user that add net6.0 and net8.0 to the project, so I could take a look and see if I can modify it to use those builds for the tasks. I can try to get it into the next release if you don't mind helping to test the functionality before I release it' I'm going away in 20 days and would hate to leave the community with no support on a new version in case I miss anything in testing.

**Comment by bakerhillpins** [comment]
@failwyn 

> It's the correct package, 

Ok, I'll take your word for it but it's clearly throwing an error from a different NuGet package based upon the directory listed in the error: 2.9.406.  (which is also out of date)
https://www.nuget.org/stats/packages/BundlerMinifier.Core?groupby=Version

This repository doesn't even publish that package as far as I can tell, that's published by the original author's repository. This repo simply builds the `.Core` code directly into the dll used.
Also, I don't have that [BundlerMinifier.Core](https://www.nuget.org/packages/BundlerMinifier.Core/) package installed anywhere that I can find on my system and this fork and Vsix package works just fine.

**Comment by failwyn** [comment]
This is the library that I publish to nuget when I release new versions of the vsix [https://www.nuget.org/packages/BuildBundlerMinifier2022](https://www.nuget.org/packages/BuildBundlerMinifier2022/) I could look into publishing BundlerMinifier.Core to nuget in the future, but I would probably have to rename it to do upload it; I'll have to see how much refactoring and testing that would require.

**Comment by mwkcoding** [comment]
It would be the core one I'd need. That's the CLI tool that allows it to be used in vscode tasks. According to the original author.

**Comment by failwyn** [comment]
@mwkcoding Would @bakerhillpins suggestion work for you in the short term if I can get the release out this week?

@bakerhillpins You're right, I wasn't aware of BundlerMinifier.Core being a nuget package; I'll look into adding that to a future release.

**Comment by failwyn** [comment]
Sorry I couldn't get it fixed for you sooner, it's tough to find time with the kids home and traveling.

**Comment by mwkcoding** [comment]
That's completely understandable. Family time is important 🙏

**Comment by failwyn** [comment]
This should work in the latest release.

**Comment by mwkcoding** [comment]
I tried installing [this](https://www.nuget.org/packages/BuildBundlerMinifier2022) as a dotnet tool. It does not seem to work. I think we'll need the core package published.

**Comment by bakerhillpins** [comment]
> I tried installing [this](https://www.nuget.org/packages/BuildBundlerMinifier2022) as a dotnet tool. It does not seem to work. I think we'll need the core package published.

I just installed and ran it. Works fine for me. What errors are you receiving?
![image](https://github.com/user-attachments/assets/c255eb98-ac52-4af0-9d64-a4ccd76e61a2)

**Comment by mwkcoding** [comment]
@bakerhillpins Oh. I tried adding it to `.csproj` like so:
```xml
<ItemGroup>
    <DotNetCliToolReference Include="BuildBundlerMinifier2022" Version="2.9.11" />
</ItemGroup>
```

But adding it like `dotnet tool install BuildBundlerMinifier2022` then it works!

**Comment by bakerhillpins** [comment]
> @bakerhillpins Oh. I tried adding it to `.csproj` like so:
> 
> ```
> <ItemGroup>
>     <DotNetCliToolReference Include="BuildBundlerMinifier2022" Version="2.9.11" />
> </ItemGroup>
> ```
> 
> But adding it like `dotnet tool install BuildBundlerMinifier2022` then it works!

Hrm.. have not seen that way to add a dotnet tool. 

You shouldn't need to manually add a reference to your project either. If you right click on the bundleconfig.json file and select `Enable Bundle On Build` that will add the project reference to your project and it will then build within VS.

**Comment by bakerhillpins** [comment]
@mwkcoding ~~Is your project properly setup for package reference or package config operation?  I think `<DotNetCliToolReference />` only works in .NET SDK projects using package references~~

Ah, that's why I don't recognize it, that feature was deprecated a long time ago. https://github.com/dotnet/sdk/issues/3115

https://stackoverflow.com/a/44173152

**Comment by mwkcoding** [comment]
I suppose our setup has been a bit wonky since the project was migrated from .NET Framework to .NET. Either way. It works by running the command! I'll close the issue.

Thanks for the help @failwyn @bakerhillpins
